/*
  Warnings:

  - You are about to drop the `Produto` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `Usuario` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
PRAGMA foreign_keys=off;
DROP TABLE "Produto";
PRAGMA foreign_keys=on;

-- DropTable
PRAGMA foreign_keys=off;
DROP TABLE "Usuario";
PRAGMA foreign_keys=on;

-- CreateTable
CREATE TABLE "USUARIO" (
    "CODUSU" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UUID" TEXT NOT NULL,
    "LOGIN" TEXT NOT NULL,
    "SENHA" TEXT NOT NULL,
    "SENHAANTIGA" TEXT NOT NULL,
    "USUINC" INTEGER,
    "USUALT" INTEGER,
    "DATINC" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DATALT" DATETIME
);

-- CreateTable
CREATE TABLE "PERFIL" (
    "CODPER" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UUID" TEXT NOT NULL,
    "PERFIL" TEXT NOT NULL,
    "USUINC" INTEGER,
    "USUALT" INTEGER,
    "DATINC" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DATALT" DATETIME
);

-- CreateTable
CREATE TABLE "USUARIOPERFIL" (
    "CODUSUPER" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UUID" TEXT NOT NULL,
    "CODUSU" INTEGER NOT NULL,
    "CODPER" INTEGER NOT NULL,
    "USUINC" INTEGER,
    "USUALT" INTEGER,
    "DATINC" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DATALT" DATETIME,
    CONSTRAINT "USUARIOPERFIL_CODUSU_fkey" FOREIGN KEY ("CODUSU") REFERENCES "USUARIO" ("CODUSU") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "USUARIOPERFIL_CODPER_fkey" FOREIGN KEY ("CODPER") REFERENCES "PERFIL" ("CODPER") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CLIENTE" (
    "CODCLI" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UUID" TEXT NOT NULL,
    "CPFCNPJ" TEXT NOT NULL,
    "NOMEFANTASIA" TEXT NOT NULL,
    "RAZAOSOCIAL" TEXT NOT NULL,
    "USUINC" INTEGER,
    "USUALT" INTEGER,
    "DATINC" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DATALT" DATETIME
);

-- CreateTable
CREATE TABLE "USUARIOCLIENTE" (
    "CODUSUCLI" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UUID" TEXT NOT NULL,
    "CODUSU" INTEGER,
    "CODCLI" INTEGER,
    "USUINC" INTEGER,
    "USUALT" INTEGER,
    "DATINC" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DATALT" DATETIME,
    CONSTRAINT "USUARIOCLIENTE_CODUSU_fkey" FOREIGN KEY ("CODUSU") REFERENCES "USUARIO" ("CODUSU") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "USUARIOCLIENTE_CODCLI_fkey" FOREIGN KEY ("CODCLI") REFERENCES "CLIENTE" ("CODCLI") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "SISTEMA" (
    "CODSIS" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UUID" TEXT NOT NULL,
    "SISTEMA" TEXT NOT NULL,
    "USUINC" INTEGER,
    "USUALT" INTEGER,
    "DATINC" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DATALT" DATETIME
);

-- CreateTable
CREATE TABLE "SISTEMACLIENTE" (
    "CODSISCLI" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UUID" TEXT NOT NULL,
    "CODSIS" INTEGER,
    "CODCLI" INTEGER,
    "USUINC" INTEGER,
    "USUALT" INTEGER,
    "DATINC" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DATALT" DATETIME,
    CONSTRAINT "SISTEMACLIENTE_CODSIS_fkey" FOREIGN KEY ("CODSIS") REFERENCES "SISTEMA" ("CODSIS") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "SISTEMACLIENTE_CODCLI_fkey" FOREIGN KEY ("CODCLI") REFERENCES "CLIENTE" ("CODCLI") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PARAMETRO" (
    "CODPARAM" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UUID" TEXT NOT NULL,
    "CHAVE" TEXT NOT NULL,
    "VALOR" TEXT NOT NULL,
    "DESCRICAO" TEXT NOT NULL,
    "CODSIS" INTEGER,
    "USUINC" INTEGER,
    "USUALT" INTEGER,
    "DATINC" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DATALT" DATETIME,
    CONSTRAINT "PARAMETRO_CODSIS_fkey" FOREIGN KEY ("CODSIS") REFERENCES "SISTEMA" ("CODSIS") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "LOGDETRANSACAO" (
    "CODEXC" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UUID" TEXT NOT NULL,
    "METODO" TEXT,
    "ROTA" TEXT,
    "ENVIO" TEXT,
    "RETORNO" TEXT,
    "CODSIS" INTEGER,
    "CODUSU" INTEGER,
    "USUINC" INTEGER,
    "USUALT" INTEGER,
    "DATINC" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DATALT" DATETIME,
    CONSTRAINT "LOGDETRANSACAO_CODSIS_fkey" FOREIGN KEY ("CODSIS") REFERENCES "SISTEMA" ("CODSIS") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "LOGDETRANSACAO_CODUSU_fkey" FOREIGN KEY ("CODUSU") REFERENCES "USUARIO" ("CODUSU") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "BLACKLIST" (
    "CODBLAC" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UUID" TEXT NOT NULL,
    "TOKEN" TEXT NOT NULL,
    "CODUSU" INTEGER,
    "USUINC" INTEGER,
    "USUALT" INTEGER,
    "DATINC" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DATALT" DATETIME,
    CONSTRAINT "BLACKLIST_CODUSU_fkey" FOREIGN KEY ("CODUSU") REFERENCES "USUARIO" ("CODUSU") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "USUARIO_UUID_key" ON "USUARIO"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "PERFIL_UUID_key" ON "PERFIL"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "USUARIOPERFIL_UUID_key" ON "USUARIOPERFIL"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "CLIENTE_UUID_key" ON "CLIENTE"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "USUARIOCLIENTE_UUID_key" ON "USUARIOCLIENTE"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "SISTEMA_UUID_key" ON "SISTEMA"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "SISTEMACLIENTE_UUID_key" ON "SISTEMACLIENTE"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "PARAMETRO_UUID_key" ON "PARAMETRO"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "LOGDETRANSACAO_UUID_key" ON "LOGDETRANSACAO"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "BLACKLIST_UUID_key" ON "BLACKLIST"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "BLACKLIST_TOKEN_key" ON "BLACKLIST"("TOKEN");
