-- CreateTable
CREATE TABLE "Lancamentos" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "CODIGO" TEXT NOT NULL,
    "TIPO" TEXT NOT NULL,
    "DATA_COMPETENCIA" DATETIME NOT NULL,
    "DATA_BAIXA" DATETIME NOT NULL,
    "VALOR" TEXT NOT NULL,
    "CLASS_ID" INTEGER NOT NULL,
    "SITUACAO" TEXT NOT NULL,
    "NATU_ID" INTEGER,
    CONSTRAINT "Lancamentos_CLASS_ID_fkey" FOREIGN KEY ("CLASS_ID") REFERENCES "Classificacao" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Lancamentos_NATU_ID_fkey" FOREIGN KEY ("NATU_ID") REFERENCES "Natureza" ("ID") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Classificacao" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "CLASSIFICACAO" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Natureza" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "NATUREZA" TEXT NOT NULL,
    "CLASS_ID" INTEGER,
    CONSTRAINT "Natureza_CLASS_ID_fkey" FOREIGN KEY ("CLASS_ID") REFERENCES "Classificacao" ("ID") ON DELETE SET NULL ON UPDATE CASCADE
);
